version: '3'

services:
  earthcpr-backend:
    build:
      context: ./earthcpr
    image: earthcpr-backend
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - earthcpr_network

networks:
  earthcpr_network:

volumes:
  mysql_data:  # MySQL 데이터를 저장하는 볼륨 정의
