name: CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'earthcpr/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Create directory for application.yml
      run: mkdir -p ./earthcpr/src/main/resources

    - name: Set up application-local.properties
      run: echo "${{ secrets.APPLICATION }}" > ./earthcpr/src/main/resources/application-local.properties
    
    - name: Grant execute permission for gradlew
      run: chmod +x ./earthcpr/gradlew

    - name: Build with Gradle
      run: ./earthcpr/gradlew build -x test

    - name: Build the Docker image
      run: docker build ./earthcpr --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/earthcpr-backend:latest

    - name: Login to Docker Hub using Access Token
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/earthcpr-backend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        PORT: 22
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/earthcpr-backend:latest
          docker stop earthcpr-backend || true
          docker rm earthcpr-backend || true
          docker run -d --name earthcpr-backend -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/earthcpr-backend:latest
        '
