== Save

=== 적금 상품 등록
operation::save-controller-test/create-savings-product-test[snippets='http-request,request-fields,http-response,response-fields']

=== 적금 상품 조회
operation::save-controller-test/get-saving-products-test[snippets='http-request,http-response,response-fields']

=== 적금 계좌 생성
operation::save-controller-test/create-savings-account-test[snippets='http-request,request-fields,http-response,response-fields']

=== 적금 계좌 목록 조회
operation::save-controller-test/get-saving-accounts-test[snippets='http-request,request-fields,http-response,response-fields']

=== 적금 계좌 조회
operation::save-controller-test/get-saving-product-detail-test[snippets='http-request,request-fields,http-response,response-fields']

=== 적금 납입 회차 조회
operation::save-controller-test/get-payment-list-test[snippets='http-request,request-fields,http-response,response-fields']

=== 만기 이자 조회
operation::save-controller-test/inquire-expiry-interest-test[snippets='http-request,request-fields,http-response,response-fields']

=== 중도 해지 이자 조회
operation::save-controller-test/inquire-early-interest-test[snippets='http-request,request-fields,http-response,response-fields']

=== 중도 해지
operation::save-controller-test/delete-account-test[snippets='http-request,request-fields,http-response,response-fields']